# Generated by Django 5.1.4 on 2024-12-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_purchase_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="date",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="total_price",
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="person",
            field=models.CharField(max_length=100),
        ),
    ]
